name: Pull Request CI Workflow
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      ## Set vars
      ## ${GITHUB_REF#refs/heads/} for push of branch
      ## OR
      ## ${GITHUB_REF#refs/tags/} for a tag
      ## Do not use ${GITHUB_REF##*} as that does not work
      ## with gitflow naming (e.g. feature/my-cool-feature)
      - name: Checkout branch
        uses: actions/checkout@v1        
      ## This installs the correct node version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      ## This runs multiple commands to run.
      - name: npm ci, build, and test
        run: |
          npm ci
          CI="" npm run build
          npm test          
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
      ## Echo build information to file
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: build
         