name: Push CI Workflow
on:
  ## This tries to avoid unessesary pushes to forked repo
  ## development branches. No sense in a dev building every
  ## time they push for a PR and no one should be working on
  ## common branches in their fork.
  push:
    branches:
      - master
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'feature/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      ## Set vars
      ## ${GITHUB_REF#refs/heads/} for push of branch
      ## 
      ## OR
      ## ${{ github.event.pull_request.number }}
      ## if the PR is under the right conditions
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Set build_name
        id: build_name
        run: echo ::set-output name=build::$(sed -E 's/refs\/(heads|tags)\///; s/\//_/g;' <<< $GITHUB_REF)
      - name: Test Build name
        run: echo ${{ steps.build_name.outputs.build }}
      ## This installs the correct node version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      ## This runs multiple commands to run.
      - name: npm ci, build, and test
        run: |
          npm ci
          CI="" npm run build
          npm test          
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
      ## Echo build information to file
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: build
         